[package]
name = "gildedrose"
version = "0.1.0"
edition = "2021"

[dependencies]
insta = { version = "1.41.1", features = ["yaml"] }
serde = { version = "1.0.215", features = ["derive"] }

[profile.dev.package]
similar.opt-level = 3
insta.opt-level = 3
